export const FETCH_USER_TOKEN_REQUEST = "FETCH_USER_TOKEN_REQUEST";
export const FETCH_USER_TOKEN_FAILURE = "FETCH_USER_TOKEN_FAILURE";
export const FETCH_USER_TOKEN_SUCCESS = "FETCH_USER_TOKEN_SUCCESS";
export const FETCH_USER_ACCESS_REQUEST = "FETCH_USER_ACCES_REQUEST";
export const FETCH_USER_ACCESS_SUCCESS = "FETCH_USER_ACCES_SUCCESS";
export const FETCH_USER_ACCESS_FAILURE = "FETCH_USER_ACCES_FAILURE";
